-- DDL InLock

CREATE DATABASE InLock_Games_Manha

USE InLock_Games_Manha

CREATE TABLE Estudios(
idEstudio INT PRIMARY KEY IDENTITY,
NomeEstudio VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Jogos(
idJogo INT PRIMARY KEY IDENTITY,
NomeJogo VARCHAR (200) NOT NULL UNIQUE,
Descricao VARCHAR(1000) NOT NULL,
DataLancamento DATE NOT NULL,
Valor DECIMAL NOT NULL,
idEstudio INT FOREIGN KEY REFERENCES Estudios(idEstudio)
);

CREATE TABLE TipoUsuario(
idTipoUsuario INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Usuario (
idUsuario INT PRIMARY KEY IDENTITY,
Email VARCHAR(100) NOT NULL UNIQUE,
Senha VARCHAR (20) NOT NULL,
idTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(idTipoUsuario)
);
